package org.projectbarry.pbosinstaller.root

/** Pieces every root job script shares. */
object ScriptKit {
    /** Single-quoted for sh. */
    fun quote(s: String): String = "'" + s.replace("'", "'\\''") + "'"

    /**
     * The start of every job script: moves itself to /data/local/tmp and into the
     * background (so "Run Script as Root" and xsu return at once, and a system server
     * restart can't kill it for having a file open on shared storage), then defines
     * status/fail/ge.
     *
     * [status] writes the status file (key=value lines, replaced atomically, handed to
     * the app's folder owner so the app can read it); extra lines go in $EXTRA.
     * [ge] compares whole numbers of any size: Android's shell does 32-bit arithmetic
     * and toybox expr's comparisons go wrong on big numbers.
     */
    fun prelude(name: String, id: String, statusFile: String, dryRun: Boolean = false): String {
        val run = "/data/local/tmp/pbos-$name.sh"
        val detach = if (dryRun) "" else """
RUN_COPY=${quote(run)}
if [ "${'$'}0" != "${'$'}RUN_COPY" ]; then
  cp "${'$'}0" "${'$'}RUN_COPY" && { nohup sh "${'$'}RUN_COPY" >/dev/null 2>&1 & }
  exit 0
fi
trap 'rm -f "${'$'}RUN_COPY"' EXIT
"""
        return """
#!/system/bin/sh
# PB-OS Installer root job "$name". Generated by the app; run as root.
set -o pipefail
$detach
JOB=${quote(id)}
STATUS=${quote(statusFile)}
EXTRA=
OWNER=${'$'}(stat -c %u:%g "${'$'}(dirname "${'$'}STATUS")" 2>/dev/null)
give() { # hand files to the app (the owner of its folder)
  [ -z "${'$'}OWNER" ] || chown "${'$'}OWNER" "${'$'}@" 2>/dev/null
  chmod 660 "${'$'}@" 2>/dev/null
}
status() { # state done total message
  { printf 'job=%s\nstate=%s\ndone=%s\ntotal=%s\nmessage=%s\n' "${'$'}JOB" "${'$'}1" "${'$'}{2:-0}" "${'$'}{3:-0}" "${'$'}4"
    [ -z "${'$'}EXTRA" ] || printf '%s\n' "${'$'}EXTRA"; } > "${'$'}STATUS.tmp" &&
    { give "${'$'}STATUS.tmp"; mv -f "${'$'}STATUS.tmp" "${'$'}STATUS"; }
}
fail() { status failed 0 0 "${'$'}1"; exit 1; }
ge() {
  [ ${'$'}{#1} -ne ${'$'}{#2} ] && { [ ${'$'}{#1} -gt ${'$'}{#2} ]; return; }
  [ "${'$'}1" = "${'$'}2" ] || [[ "${'$'}1" > "${'$'}2" ]]
}
sha() { sha256sum "${'$'}@" | cut -d' ' -f1; }
status started
""".trimStart()
    }
}
